### ISSUE TITLE
Document jsxRenderer <Layout> Props for Additional Handler Context

### ISSUE THREAD

**Issue by Luzefiru** [honojs/honox#106]
### What is the feature you are proposing?

Add documentation on how we must pass any [ContextRenderer](https://hono.dev/middleware/builtin/jsx-renderer#extending-contextrenderer) props to a nested `jsxRenderer` found in an `/app/routes/nested/_renderer.tsx` path `<Layout />` to make it propagate to the parent `/app/routes/_renderer.tsx`. Because currently, the documentation doesn't take note of the edge case where a nested renderer's route may have additional context which is passed from the route `Handler`.

## Background

I was implementing nested layouts in my HonoX application following [this documentation](https://github.com/honojs/honox?tab=readme-ov-file#nested-layouts) on the official HonoX repository.

When my root `_renderer.tsx` uses a `export default jsxRenderer(({ children, title })` and the `title` parameter so that my routes can set the title as additional renderer props, it does not automatically pick it up unless we pass it as props inside the nested renderer's `export default jsxRenderer(({ children, Layout, title })` `<Layout />` like this:

```tsx
// /app/routes/nested/_renderer.tsx
export default jsxRenderer(({ children, Layout, title }) => {
  return (
    <Layout title={title}> {/* this was not documented */}
      <Navbar />
      <Sidebar />
      <main className="p-4 bg-gray-100 sm:ml-64">{children}</main>
    </Layout>
  );
});
```

```tsx
// /app/routes/_renderer.tsx
import { jsxRenderer } from 'hono/jsx-renderer';
import { Style } from 'hono/css';
import { Script } from 'honox/server';

export default jsxRenderer(({ children, title }) => {
  return (
    <html lang="en">
      <head>
        <title>{title}</title> {/* we consume it here */}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <Script src="/app/client.ts" />
        <Style />
        {import.meta.env.PROD ? (
          <link rel="stylesheet" href="/static/assets/style.css" />
        ) : (
          <link rel="stylesheet" href="/app/style.css" />
        )}
      </head>
      <body>
        {children}
      </body>
    </html>
  );
});
```

**Comment by yusukebe** [comment]
Hi @Luzefiru !

I think one of the problems is that the following `title` is not typed.

```tsx
<Layout title={title}> {/* this was not documented */}
```

If so, it's a bug in Hono core.

**Comment by yusukebe** [comment]
Besides, you are right, we should add that to the document.

**Comment by Luzefiru** [comment]
> I think one of the problems is that the following `title` is not typed.

It's typed in my `/app/global.d.ts` like so:

```ts
import {} from 'hono';

type Head = {
  title?: string;
};

declare module 'hono' {
  interface Env {
    Variables: {};
    Bindings: {};
  }
  interface ContextRenderer {
    (content: string | Promise<string>, head?: Head):
      | Response
      | Promise<Response>;
  }
}
```

Issue is when I try to pass the title as an additional renderer context on a route handler like this:

```tsx
export default createRoute((c) => {
  return c.render(<Dashboard />, { title: 'Dashboard' });
});
```

```tsx
export default jsxRenderer(({ children, Layout }) => {
  return (
    <Layout> {/* this doesn't pass the title, so the title argument I passed to c.render() is lost */}
      <Navbar />
      <Sidebar />
      <main className="p-4 bg-gray-100 sm:ml-64">{children}</main>
    </Layout>
  );
});
```

My renderer doesn't use the `{ title: 'Dashboard' }` like I want it to unless I manually accept the title prop again in the nested renderer. This fixes the issue:

```tsx
export default jsxRenderer(({ children, Layout, title }) => {
  return (
    <Layout title={title}> {/* now my title works in the parent renderer */}
      <Navbar />
      <Sidebar />
      <main className="p-4 bg-gray-100 sm:ml-64">{children}</main>
    </Layout>
  );
});
```

**Comment by yusukebe** [comment]
@Luzefiru 

Thanks. I fully understand!
