### ISSUE TITLE
Routing priority

### ISSUE THREAD

**Issue by yusukebe** [honojs/honox#131]
### What is the feature you are proposing?

If we have these routes:

```
GET   /note/:id
GET   /note/create
```

`/note/:id` should not override `/note/create`.  But currently, maybe not.

**Comment by yusukebe** [comment]
Hi @bruceharrison1984 

I was busy with the business trip, but I will work on this soon! Or will you fix it (maybe not so difficult)?

**Comment by bruceharrison1984** [comment]
No rush from me 😄

I took a look at the source and have a few ideas, but haven't tried anything yet.

**Comment by yusukebe** [comment]
@bruceharrison1984 

Okay, no problem!

**Comment by bruceharrison1984** [comment]
Checkout PR #137
