### ISSUE TITLE
Support named export not only `default` in Islands

### ISSUE THREAD

**Issue by yusukebe** [honojs/honox#156]
### What is the feature you are proposing?

Currently, to make it an island component, it should exported as `default`:

```tsx
export default function Badge({ name }: PropsWithChildren<{ name: string }>) {
  return <div>Hey {name}</div>
}
```

But it's not convenient if we can only use `default` export. Ideally, for example, exported by `Badge` also should be treated as island:

```tsx
export function Badge({ name }: PropsWithChildren<{ name: string }>) {
  return <div>Hey {name}</div>
}
```

I think we can do it by referring to Astro. The HTML rendered by Astro is like the following:

```html
<astro-island uid="1SNFe8" prefix="r0" component-url="/src/components/Badge.tsx" component-export="Badge" renderer-url="/node_modules/.vite/deps/@astrojs_react_client__js.js?v=179f417c" props="{&quot;name&quot;:[0,&quot;Hello&quot;]}" ssr="" client="load" before-hydration-url="/@id/astro:scripts/before-hydration.js" opts="{&quot;name&quot;:&quot;Badge&quot;,&quot;value&quot;:true}" server-render-time="1.5938749313354492" await-children="">
  <div>
      Hey 
      <!-- -->
      Hello<hr/>
  </div>
  <!--astro:end-->
</astro-island>
```

It's a good idea to use the `component-export`.

**Comment by alxhotel** [comment]
Really looking forward to this feature!

I'm new to the codebase, so I'm not sure where to look, but let me know if you want some help
