### ISSUE TITLE
routing for .well-known is 404

### ISSUE THREAD

**Issue by Jxck** [honojs/honox#179]
### What version of HonoX are you using?

0.1.17

### What steps can reproduce the bug?

create `app/routes/.well-known/security.txt.tsx` as below

```ts
import { createRoute } from "honox/factory"

export default createRoute(async (c) => {
  return c.text(
    `
Contact: ${c.env.ContactEmail}
Expires: 2025-12-31T14:55:00.000Z
    `.trim()
  )
})
```

and access to https://host.example/.well-known/security.txt returns 404

but renaming directory to `app/routes/well-known/security.txt.tsx` (removing `.` from `well-known`) and accessing `https://host.example/well-known/security.txt` returns 200 as expected.

It seems that, name based routing failed with prefix of `.` for `well-known`.

FYI: `.well-known/` is important path for serving various of standard defined files.
https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

**Comment by yusukebe** [comment]
Hi @Jxck

This was fixed. You can try the new version `0.1.18` that includes the fix. Thanks!
