### ISSUE TITLE
Better `EventAttributes` types

### ISSUE THREAD

**Issue by dinfer** [honojs/honox#203]
### What is the feature you are proposing?

```
<input
          placeholder="username"
          onChange={(e) => {
            model.username = e.target.value; // Property 'value' does not exist on type 'EventTarget'.ts(2339)
          }}
        />
```

**Comment by yusukebe** [comment]
Hi @dinfer 

This is a good issue and is the same with https://github.com/honojs/hono/issues/2491

**Comment by yusukebe** [comment]
We can close this issue because this is the same as https://github.com/honojs/hono/issues/2491 . Thanks.
