### ISSUE TITLE
Cloudflare dependencies is included when is not used

### ISSUE THREAD

**Issue by jlucaso1** [honojs/honox#205]
### What version of HonoX are you using?

0.1.23

### What steps can reproduce the bug?

Install hono, honox, vite and @hono/vite-dev-server
Check node_modules after install and will be like:
![image](https://github.com/user-attachments/assets/670178ca-9f7d-42f0-a96c-b715be8c1760)

### What is the expected behavior?

The cloudflare dependencies don't need to be downloaded or included in node_modules

### What do you see instead?

A high usage of disk in node_modules. This can improve installs on CI/CD enviroments in general

### Additional information

I'm using bun, but this bug occurs also in NPM

**Comment by yusukebe** [comment]
Hi @jlucaso1 

Thank you for the issue. It's a known issue for `@hono/vite-dev-server`. It depends `miniflare` to keep 
backward compatibility:

https://github.com/honojs/vite-plugins/blob/fdd4b48e7833156360097960fe1dca0bbcafd845/packages/dev-server/package.json#L79

But, now, we may mind the backward compatibility. If so, we can remove it. Please wait a little to consider it.

**Comment by yusukebe** [comment]
Now, `@hono/vite-dev-server` does not depend on `miniflare`. We can close this issue. Thanks!
