### ISSUE TITLE
Documentation - Starter Template - No x-basic option in hono-create command

### ISSUE THREAD

**Issue by laurentlahmy** [honojs/honox#212]
### What version of HonoX are you using?

latest

### What steps can reproduce the bug?

https://github.com/honojs/honox?tab=readme-ov-file#starter-template

### What is the expected behavior?

 hono-create command should have a x-basic option?

**Comment by yusukebe** [comment]
Hi @laurentlahmy 

`create-hono` has a `x-basic` option: 

![CleanShot 2024-08-11 at 23 12 47@2x](https://github.com/user-attachments/assets/ef8256c4-babe-4667-a97b-84f22441b5ef)

Can you try it again?

**Comment by laurentlahmy** [comment]
ah right I didn't see the arrow keys option, maybe it's a bit unexpected? 
<img width="331" alt="image" src="https://github.com/user-attachments/assets/2aae0d92-f3f4-4ace-a753-2dd62fb28928">
