### ISSUE TITLE
Where should static assets be stored?

### ISSUE THREAD

**Issue by onlyfortesting** [honojs/honox#218]
### What version of HonoX are you using?

0.1.24

### What steps can reproduce the bug?

In fresh `x-basic` template, any assets under `public` directory can't be accessed except `/favicon.ico`. If I were to use `static` directory and access it via `/static/image.jpg`, it works. But that’s confusing because `public` and `static` essentially serve the same purpose.

### What is the expected behavior?

can access assets under `public` directory e.g. `/image.jpg`

### What do you see instead?

404 not found

### Additional information

using this vite config as workaround:
```js
{
    plugins: [
      honox({
        devServer: {
          adapter,
          exclude: [
            ...devServerDefaultOptions.exclude,
            /^\/app\/.+/,
            /^\/favicon.ico/,
            /^\/static\/.+/,
            /\.(png|jpg|jpeg|svg|webp)$/, // added
          ],
        },
      }),
      pages(),
    ],
}
```

**Comment by yusukebe** [comment]
Hi @onlyfortesting 

Sorry for the late response. Your workaround is a good solution. It's a little bit annoying, but please use it.
