### ISSUE TITLE
vite-tsconfig-paths compatibility

### ISSUE THREAD

**Issue by Mushus** [honojs/honox#222]
### What version of HonoX are you using?

0.1.23

### What steps can reproduce the bug?

When an island component is called from a component imported via an alias defined by vite-tsconfig-paths, the child elements of the `HasIslands` component never render.

1. Create an x-basic project:
  ```npm create hono@latest```
2. Install `vite-tsconfig-paths`:
  ```npm i -D vite-tsconfig-paths```
3. Define `compilerOptions.paths` in `tsconfig.json`:
    ```diff
    {
      "compilerOptions": {
      ︙
    +  "baseUrl": ".",
    +  "paths": {
    +    "@/*": ["app/*"]
    +  }
      }
      ︙
    }
    ```
4. Add `vite-tsconfig-paths` plugin to `vite.config.ts`:
    ```diff
    ︙
    +import tsconfigPaths from "vite-tsconfig-paths";
    
    export default defineConfig({
      plugins: [
        ︙
   +    tsconfigPaths()
      ],
    });
    ```
5. Create a component `app/SomeComponent.tsx` :
    ```tsx
    import Counter from "./islands/counter";
    export default function SomeComponent() {
      return <Counter />;
    }
    ```
6. Update `app/index.tsx` to render SomeComponent:
    ```diff
    ︙
    -import Counter from "../islands/counter";
    +import SomeComponent from "@/SomeComponent";
    ︙
    export default createRoute((c) => {
      ︙
      return c.render(
        ︙
    -      <Counter />
    +      <SomeComponent />
        ︙
      );
    });
    ```
7. (Optional) If we want to check in the dev build, we add the HasIslands component in `app/routes/_renderer.tsx`:
    ```diff
    ︙
    export default jsxRenderer(({ children, title }) => {
      return (
        ︙
    -        <Script src="/app/client.ts" async />
    +        <HasIslands>
    +          <Script src="/app/client.ts" async />
    +        </HasIslands>
        ︙
      );
    });
    ```

### What is the expected behavior?

When an island component is used, the child elements of the `HasIslands` component are rendered.

### What do you see instead?

It can be avoided by defining resolve.alias in the vite.config.ts file instead.

### Additional information

This means that the `honox/server` `Script` component, as well as this issue, will not work properly with the island component in production builds.

**Comment by yusukebe** [comment]
Hi @Mushus 

Thank you for the issue. I've fixed and released the new version `v0.1.26`. Try it.
