### ISSUE TITLE
_middleware.ts is not loaded for deeply nested param routes

### ISSUE THREAD

**Issue by jakelee8** [honojs/honox#228]
### What version of HonoX are you using?

0.1.25

### What steps can reproduce the bug?

1. Add `_middleware.ts` with `console.log()` to `app/routes/organizations/[organizationId]/products/[productId]`
2. Add `index.tsx` to `app/routes/organizations/[organizationId]/products/[productId]`
3. Navigate to `/organizations/:organizationId/products/:productId` and see that the log is not shown

### What is the expected behavior?

Deeply nested param routes load the `_middleware.ts` file.

### What do you see instead?

`_middleware.ts` file is not loaded for deeply nested param routes.

### Additional information

This bug is related to https://github.com/honojs/honox/issues/184

Using `replaceAll` instead of `replace` fixes the issue.

https://github.com/honojs/honox/blob/main/src/server/server.ts#L138

**Comment by yusukebe** [comment]
Hi @jakelee8

Thank you for the issue. I've fixed and released the new version `v0.1.26`. Try it!
