### ISSUE TITLE
SSG is broken

### ISSUE THREAD

**Issue by jlarmstrongiv** [honojs/honox#234]
### What version of HonoX are you using?

v0.1.26

### What steps can reproduce the bug?

Follow the instructions in the [README](https://github.com/honojs/honox?tab=readme-ov-file#ssg---static-site-generation)

### What is the expected behavior?

The `dist` folder contains html pages

### What do you see instead?

Only client .js files and the favicon exist in the `dist` folder—there is no html to be found.

**Comment by yusukebe** [comment]
HI @jlarmstrongiv 

Sorry for the late response. This was fixed with the new version of `hono@4.6.15` . Please try it.

**Comment by yusukebe** [comment]
I think we can close this issue because #236 which has the same problem is closed. Thanks.

**Comment by jlarmstrongiv** [comment]
The fix worked 👍
