### ISSUE TITLE
ssg fails if `_error.tsx` exists

### ISSUE THREAD

**Issue by sho-hata** [honojs/honox#236]
### What version of HonoX are you using?

0.1.26

### What steps can reproduce the bug?

1. `npm create hono@latest`
2. choose template: `x-basic`
3. Change `vite.config.ts` as in https://github.com/honojs/honox?tab=readme-ov-file#ssg---static-site-generation
4. `bun run build`

### What is the expected behavior?

index.html is output to `dist/`.
```
dist
├── .vite
├── articles
├── static
├── _routes.json
├── _worker.js
├── favicon.ico
└── index.html
```

### What do you see instead?

index.html is not output to `dist/`. No error message will be displayed.

```
dist
├── .vite
├── articles
├── static
├── _routes.json
├── _worker.js
└── favicon.ico
```

### Additional information

- If you delete `error.tsx`, ssg build is successfully performed and index.html is generated
- The `_error.tsx` file generated by the honox template is treated as a special file in hono because it's used for creating custom error handlers. 
https://github.com/honojs/honox/blob/034cd200655308881f3557bef8fca441b07c7f9c/src/server/server.ts#L192
I suspect that this might be affecting the SSG build process.

**Comment by sho-hata** [comment]
Maybe it has something to do with this issue: https://github.com/honojs/honox/issues/234

**Comment by yusukebe** [comment]
Hi @sho-hata 

Sorry for the late response. This was fixed with the new version of `hono@4.6.15` . Can you try it?

**Comment by sho-hata** [comment]
Hello, @yusukebe 
Thank you for resolving this issue! I appreciate the effort you put into addressing the problem.
Everything works as expected in my testing.

**Comment by yusukebe** [comment]
@sho-hata 

Good! I'll close this issue! Thank you.
