### ISSUE TITLE
Directories with leading dot are ignored

### ISSUE THREAD

**Issue by bruceharrison1984** [honojs/honox#36]
Not sure if this goes here or over at Vite, since the problem stems from their side. See the following discussion post I made over there:

https://github.com/vitejs/vite/discussions/15859

I wasn't sure if it was possible to alter the globbing pattern or add an additional one from the context of this plugin to additionally add those hidden/dot files back in.

I don't know how flexible `fast-glob` is, but could something similar to this work?
https://askubuntu.com/a/1452417

---

One work-around here is to just create a Hono router in the directory and manually create the path (avoiding using directories), so there is a path forward if this cannot be fixed at this level.

Great work on this regardless!

**Comment by yusukebe** [comment]
Hi @bruceharrison1984 

Yeah, that's a Vite's matter. So, I would like to wait for the Vite side to respond.

The work-around means creating `app/routes/.well-known.ts` and write like this?:

```ts
import { Hono } from 'hono'

const app = new Hono()

app.get('/foo.txt', (c) => {
  return c.text('Foo')
})

export default app
```

I think this is a good solution and we can do almost things with this.

**Comment by bruceharrison1984** [comment]
That's what I was thinking as well. I'll go ahead and close this.
