### ISSUE TITLE
Middleware registered in `server.ts` doesn't work

### ISSUE THREAD

**Issue by bruceharrison1984** [honojs/honox#37]
- Create a new app using `npm create hono@latest` 
- Select `x-basic`
- Alter `server.ts` to include some middleware:

```ts
//app/server.ts

import { cors } from 'hono/cors';
import { createApp } from 'honox/server';
import { poweredBy } from 'hono/powered-by';
import { secureHeaders } from 'hono/secure-headers';
import { showRoutes } from 'hono/dev';
import { timing } from 'hono/timing';

const app = createApp();
app.use(
  cors(),
  secureHeaders(),
  timing(),
  poweredBy(),
  (ctx, next) => {
    console.log('middleware!');
    return next();
  }
);

showRoutes(app);

export default app;

```

Upon running, none of the middleware seems to be working. None of the response headers are altered per the middleware. This can also be verified because the `middleware!` text is never logged to the output.

**Comment by mipopon** [comment]
What I found working was that you create a Hono instance before and pass it to `createApp` function.

```ts
const base = new Hono<AppEnv>();

base.use(authMiddleware, envMiddleware);

const app = createApp({ app: base });

showRoutes(app);

export default app;

```

**Comment by bruceharrison1984** [comment]
@mipopon Ah, ok that makes sense. Thanks!
