### ISSUE TITLE
In the honox-island tag, SVG does not display properly

### ISSUE THREAD

**Issue by zxpzdtom** [honojs/honox#71]
### What version of HonoX are you using?

0.1.3

### What steps can reproduce the bug?

![image](https://github.com/honojs/honox/assets/22407004/cb70a6ad-7cab-4e52-b24e-e0ca753b70b4)

SVG tags do not render properly when they are in ﻿`honox-island`.

### What is the expected behavior?

Render SVG normally

### What do you see instead?

SVG does not display properly

**Comment by yusukebe** [comment]
Hi @zxpzdtom !

This is a "hono" matter, and thanks to @usualoma , this issue will be fixed. Upgrade `hono` and try it!
