### ISSUE TITLE
Whole source code directory is being served as static assets?

### ISSUE THREAD

**Issue by BasWilson** [honojs/honox#97]
### What version of HonoX are you using?

0.1.5

### What steps can reproduce the bug?

I have no idea how to reproduce, did not touch anything. But out of nowhere all my source code files are being served as static files it seems. 

After removing node_modules and reinstalling all is good again.

### What is the expected behavior?

For the backend code to not load in the application and file tree to look like this:

<img width="237" alt="image" src="https://github.com/honojs/honox/assets/20173573/02fc7a51-8fb6-486b-947b-9a893c393850">

### What do you see instead?

The sources tree in devtools: 
<img width="238" alt="image" src="https://github.com/honojs/honox/assets/20173573/ec80f35e-404b-4b97-b294-9c0112af31e2">

And these console logs in the browser for sqlite code (db related code that should not be called here): 
```bash
better-sqlite3.js?v=045ece3c:422 Uncaught (in promise) TypeError: promisify is not a function
    at node_modules/better-sqlite3/lib/methods/backup.js (better-sqlite3.js?v=045ece3c:422:20)
    at __require2 (chunk-624QZG55.js?v=045ece3c:16:50)
    at node_modules/better-sqlite3/lib/database.js (better-sqlite3.js?v=045ece3c:841:33)
    at __require2 (chunk-624QZG55.js?v=045ece3c:16:50)
    at node_modules/better-sqlite3/lib/index.js (better-sqlite3.js?v=045ece3c:859:22)
    at __require2 (chunk-624QZG55.js?v=045ece3c:16:50)
    at better-sqlite3.js?v=045ece3c:863:16
```

### Additional information

Been playing around with HonoX for a couple days without this issue. Only just happened.

vite.config.ts:

```ts
import pages from '@hono/vite-cloudflare-pages'
import honox from 'honox/vite'
import { defineConfig } from 'vite'

export default defineConfig(({ mode }) => {
  if (mode === 'client') {
    return {
      build: {
        rollupOptions: {
          input: ['/app/style.css'],
          output: {
            assetFileNames: 'static/assets/[name].[ext]'
          }
        }
      }
    }
  } else {
    return {
      ssr: {
        // if node modules use commonjs, add them here. 
        external: ['better-sqlite3']
      },
      plugins: [honox(), pages()]
    }
  }
})
```

**Comment by yusukebe** [comment]
Hi @BasWilson 

Please create a minimum project that can be reproduced. Otherwise, we will not be able to support you.

**Comment by BasWilson** [comment]
It happens randomly when you externalise dependencies. I would say its out of HonoX's control. More an issue with vite. Thanks
